/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Help;

import Business.Enterprise.Enterprise;
import Business.Organization.ApplicationAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarOwnerWorkRequest;
import Business.WorkQueue.CarUserWorkRequest;
import Business.WorkQueue.WebsiteAdminWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class RatingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RatingJPanel
     */
    JPanel container;
    UserAccount useraccount;
    Enterprise enterprise;
    private boolean flag=true;
    private String rateme=null;
    
    
    public RatingJPanel(JPanel container,UserAccount useraccount,Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ratingjTable = new javax.swing.JTable();
        badjLabel = new javax.swing.JLabel();
        averagejLabel = new javax.swing.JLabel();
        goodjLabel = new javax.swing.JLabel();
        awesomejLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Rating");

        ratingjTable.setBackground(new java.awt.Color(153, 204, 255));
        ratingjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rider", "Car", "Source", "Destination", "Requested Date"
            }
        ));
        jScrollPane1.setViewportView(ratingjTable);

        badjLabel.setBackground(new java.awt.Color(255, 255, 255));
        badjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/onerating.png"))); // NOI18N
        badjLabel.setToolTipText("");
        badjLabel.setOpaque(true);
        badjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badjLabelMouseClicked(evt);
            }
        });

        averagejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tworating.png"))); // NOI18N
        averagejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                averagejLabelMouseClicked(evt);
            }
        });

        goodjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/threerating.png"))); // NOI18N
        goodjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goodjLabelMouseClicked(evt);
            }
        });

        awesomejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourrating.png"))); // NOI18N
        awesomejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                awesomejLabelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Bad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Average");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Good");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Awesome");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submitblackbutton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(badjLabel)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(87, 87, 87)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(averagejLabel)
                                .addGap(35, 35, 35)
                                .addComponent(goodjLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel8)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awesomejLabel)
                            .addComponent(jLabel9))
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(averagejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(goodjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(badjLabel)))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(awesomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void badjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badjLabelMouseClicked
       rateme = "Bad";
    }//GEN-LAST:event_badjLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        flag = true;
        int selectedRow = ratingjTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(rateme == null){
            JOptionPane.showMessageDialog(this, "Please select a rating.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        WorkRequest request = (WorkRequest)ratingjTable.getValueAt(selectedRow, 1);
        UserAccount user=null;
        UserAccount user1=null;
        // sending from user to owner
        if(request instanceof CarOwnerWorkRequest){
                user = request.getReceiver();  // user is ownername
                user1 = request.getSender();   //  user1 is username
        }
        // sending from owner to user
        if(request instanceof CarUserWorkRequest){
            user = request.getSender();   //  user is ownername
            user1 = request.getReceiver(); // user1 is username

        }
        /******/
        for(Organization org :enterprise.getOrganizationDirectory().getOrganizationList())
        {if(org instanceof ApplicationAdminOrganization)
            {
                for(WorkRequest wr : org.getWorkQueue().getWorkRequestList())
                    if((wr.getSender().equals(user1)) && (wr.getReceiver().equals(user)))
                    {
                        JOptionPane.showMessageDialog(this, "Already rating is published");
                        flag = false;
                        break;
                    }
            }
        }   
            
        /****/
            if(flag)
            {
        WebsiteAdminWorkRequest req = new WebsiteAdminWorkRequest();
        req.setReceiver(user); // receiver is the owner
        req.setRating(rateme);
        req.setSender(useraccount); // sender is the user sending
        req.setRequestDate(new Date());
        ((WebsiteAdminWorkRequest) req).setMarkit(true);
        ((WebsiteAdminWorkRequest) req).setStatus("Waiting");
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ApplicationAdminOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(req);
            useraccount.getWorkQueue().getWorkRequestList().add(req);
        }
        
        JOptionPane.showMessageDialog(this, "Rating has been sent to administrator. Thank You.","Information",JOptionPane.INFORMATION_MESSAGE);
        flag = true;
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void averagejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_averagejLabelMouseClicked
        rateme = "Average";
    }//GEN-LAST:event_averagejLabelMouseClicked

    private void goodjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goodjLabelMouseClicked
        rateme = "Good";
    }//GEN-LAST:event_goodjLabelMouseClicked

    private void awesomejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_awesomejLabelMouseClicked
        rateme = "Awesome";
    }//GEN-LAST:event_awesomejLabelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_jButton2ActionPerformed

    public void populatetable()
    {
        DefaultTableModel model = (DefaultTableModel) ratingjTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : useraccount.getWorkQueue().getWorkRequestList()){
          if(request instanceof CarOwnerWorkRequest){
                if(request.getReceiver() == null)
                    //JOptionPane.showMessageDialog(this, "No user found. Wait for trip to get over.");
                {} else{
            Object[] row = new Object[5];
            row[0] = request.getReceiver();
            row[1] = request;
            row[2] = request.getSource();
            row[3] = request.getDestination();
            row[4] = request.getRequestDate();
            model.addRow(row);
            }
            }
        }
        /****/
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
            for(WorkRequest workreq :  org.getWorkQueue().getWorkRequestList())
                if(workreq instanceof CarUserWorkRequest)
                    if(workreq.getReceiver() == null)
                    {}else{
                    //if(workreq.getReceiver().equals(useraccount))
                    if(((CarUserWorkRequest) workreq).getUserlist().contains(useraccount))
                        {
                    Object[] row = new Object[5];
                     row[0] = workreq.getSender();
                     row[1] = workreq;
                     row[2] = workreq.getSource();
                     row[3] = workreq.getDestination();
                     row[4] = workreq.getRequestDate();
                     model.addRow(row);
                    }
                    }
        ratingjTable.setSelectionBackground(Color.getHSBColor(0.2F, 0.1F, 0.2F));
        ratingjTable.setSelectionForeground(Color.white);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averagejLabel;
    private javax.swing.JLabel awesomejLabel;
    private javax.swing.JLabel badjLabel;
    private javax.swing.JLabel goodjLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ratingjTable;
    // End of variables declaration//GEN-END:variables
}
