/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ApplicationAdmin;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Interface.Caruser.Pendingrequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class ApplicationAdminpanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationAdminpanel
     */
    JPanel container;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Organization orz;
    public ApplicationAdminpanel(JPanel userProcessContainer, UserAccount account, 
            Organization organization, Enterprise enterprise) {
        initComponents();
        container = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        popuatecarusertable();
        populatecarownertable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaruserrjTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarownerjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dollar10offerjButton = new javax.swing.JButton();
        dollar20offerjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Application Admin");
        add(jLabel1);
        jLabel1.setBounds(229, 32, 332, 44);

        CaruserrjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Name", "Phone No.", "Balance", "Rides"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CaruserrjTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(102, 274, 568, 88);

        CarownerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Name", "Phone No.", "Balance", "Rides"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CarownerjTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(102, 124, 568, 88);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Car Owner");
        add(jLabel2);
        jLabel2.setBounds(48, 96, 97, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Car User");
        add(jLabel3);
        jLabel3.setBounds(48, 246, 77, 22);

        jPanel1.setBackground(new java.awt.Color(254, 253, 254));

        dollar10offerjButton.setBackground(new java.awt.Color(0, 0, 0));
        dollar10offerjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dollar10offerjButton.setForeground(new java.awt.Color(255, 255, 255));
        dollar10offerjButton.setText("Offers !! 10$");
        dollar10offerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar10offerjButtonActionPerformed(evt);
            }
        });

        dollar20offerjButton.setBackground(new java.awt.Color(0, 0, 0));
        dollar20offerjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dollar20offerjButton.setForeground(new java.awt.Color(255, 255, 255));
        dollar20offerjButton.setText("Offers !! 20$");
        dollar20offerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar20offerjButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Offers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dollar10offerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dollar20offerjButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dollar10offerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar20offerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(100, 390, 262, 127);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ratings");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ratingstars.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(370, 390, 136, 127);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Analytics");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analytics.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        add(jPanel3);
        jPanel3.setBounds(530, 390, 136, 127);
    }// </editor-fold>//GEN-END:initComponents

    private void dollar10offerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar10offerjButtonActionPerformed
        UserAccount userB=null;
        UserAccount userA=null;
        int rowowner  = CarownerjTable.getSelectedRow();
        int rowuser = CaruserrjTable.getSelectedRow();
        if(rowowner>=0 && rowuser >=0)
        {
            JOptionPane.showMessageDialog(this, "Please select only one row");
            popuatecarusertable();
            populatecarownertable();
           return;
        }
        if(rowowner!=-1)
        userA = (UserAccount)CarownerjTable.getValueAt(rowowner, 0);
        if(rowuser!=-1)
            userB = (UserAccount)CaruserrjTable.getValueAt(rowuser, 0);
        String org;
        
        if((rowowner < 0) && (rowuser <0) )
        {
            JOptionPane.showMessageDialog(this, "Please select a row","Error",JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            if(rowowner>=0)
                org = "Car Owner Organization";
            else
                org = "Caruser Organization";
            
            for (Organization org1 : enterprise.getOrganizationDirectory().getOrganizationList() ){
                if(org1.getName().equals(org))
                {
                    for(UserAccount ua : org1.getUserAccountDirectory().getUserAccountList()){
                            if(ua.equals(userA)){
                                //ua.getPerson().setAmount(ua.getPerson().getAmount() + 10);
                                ua.setPayment(ua.getPayment()+10);
                                break;}
                            if(ua.equals(userB)){
                              //  ua.getPerson().setAmount(ua.getPerson().getAmount() + 10);
                                ua.setPayment(ua.getPayment()+10);
                                break;}
                    }
                }
            }
        }
        popuatecarusertable();
        populatecarownertable();
    }//GEN-LAST:event_dollar10offerjButtonActionPerformed

    private void dollar20offerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar20offerjButtonActionPerformed
        
        UserAccount userB=null;
        UserAccount userA=null;
        int rowowner  = CarownerjTable.getSelectedRow();
        int rowuser = CaruserrjTable.getSelectedRow();
        if(rowowner>=0 && rowuser >=0)
        {
            JOptionPane.showMessageDialog(this, "Please select only one row");
            popuatecarusertable();
            populatecarownertable();
           return;
        }
        if(rowowner!=-1)
        userA = (UserAccount)CarownerjTable.getValueAt(rowowner, 0);
        if(rowuser!=-1)
            userB = (UserAccount)CaruserrjTable.getValueAt(rowuser, 0);
        String org;
        
        if((rowowner < 0) && (rowuser <0) )
        {
            JOptionPane.showMessageDialog(this, "Please select a row","Error",JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            if(rowowner>=0)
                org = "Car Owner Organization";
            else
                org = "Caruser Organization";
            
            for (Organization org1 : enterprise.getOrganizationDirectory().getOrganizationList() ){
                if(org1.getName().equals(org))
                {
                    for(UserAccount ua : org1.getUserAccountDirectory().getUserAccountList()){
                            if(ua.equals(userA)){
                                //ua.getPerson().setAmount(ua.getPerson().getAmount() + 20);
                                ua.setPayment(ua.getPayment()+20);
                                break;}
                            if(ua.equals(userB)){
                                ua.setPayment(ua.getPayment()+20);
                                //ua.getPerson().setAmount(ua.getPerson().getAmount() + 20);
                                break;}
                    }
                }
            }
        }
        popuatecarusertable();
        populatecarownertable();
        
    }//GEN-LAST:event_dollar20offerjButtonActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
         AdminRatingJPanel adminrating = new AdminRatingJPanel(container,userAccount,organization);
        container.add("Confirm ride", adminrating);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        
         Analytics schedule = new Analytics(container,userAccount,organization,enterprise);
        container.add("Confirm ride", schedule);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    public void popuatecarusertable()
    {
        
        DefaultTableModel model = (DefaultTableModel) CarownerjTable.getModel();
        
        model.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList() ){
                if(org.getName().equals("Car Owner Organization"))
                {
                    for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                
                            Object[] row = new Object[5];
                            row[0] = ua;
                            row[1] = ua.getPerson().getPersonName();
                            row[2] = ua.getPerson().getPhonenumber();
                            row[3] = ua.getPayment();
                            row[4] = ua.getTrips();
                            model.addRow(row);
                    }          
                 }
         }
        
        CarownerjTable.setSelectionBackground(Color.getHSBColor(0.2F, 0.1F, 0.2F));
        CarownerjTable.setSelectionForeground(Color.white);
        
    }
    
    public void populatecarownertable()
    {
        
        DefaultTableModel model = (DefaultTableModel) CaruserrjTable.getModel();    
        
        model.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList() ){
                if(org.getName().equals("Caruser Organization"))
                {
                    for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                
                            Object[] row = new Object[5];
                            row[0] = ua;
                            row[1] = ua.getPerson().getPersonName();
                            row[2] = ua.getPerson().getPhonenumber();
                            row[3] = ua.getPayment();
                            row[4] = ua.getTrips();
                            model.addRow(row);
                    }          
                 }
         }
        
        CaruserrjTable.setSelectionBackground(Color.getHSBColor(0.2F, 0.1F, 0.2F));
        CaruserrjTable.setSelectionForeground(Color.white);
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarownerjTable;
    private javax.swing.JTable CaruserrjTable;
    private javax.swing.JButton dollar10offerjButton;
    private javax.swing.JButton dollar20offerjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
