/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TechSupport;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CarUserOrganization;
import Business.Organization.Organization;
import Business.Organization.TechnicalPersonOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TechnicalpersonworkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class Causerbugreport extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    JPanel container;
    UserAccount userAccount;
    CarUserOrganization organization;
    Enterprise enterprise;
    EcoSystem system;

    public Causerbugreport(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,Organization organization,EcoSystem system) {
        initComponents();
        this.container = userProcessContainer;
        this.userAccount = account;
        this.organization = (CarUserOrganization) organization;
        this.enterprise = enterprise;
        this.system = system;
        Date selectedDate = new Date();

        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        componentjTextField = new javax.swing.JTextField();
        issuejTextField = new javax.swing.JTextField();
        SubmitjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Car user bug report");
        add(jLabel1);
        jLabel1.setBounds(250, 30, 231, 29);

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Assigned", "User Reported", "Issue", "Component", "Resolution", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 573, 91);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Component");
        add(jLabel3);
        jLabel3.setBounds(210, 290, 104, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Issue");
        add(jLabel4);
        jLabel4.setBounds(210, 240, 50, 22);
        add(componentjTextField);
        componentjTextField.setBounds(380, 290, 110, 30);
        add(issuejTextField);
        issuejTextField.setBounds(380, 240, 110, 30);

        SubmitjButton.setBackground(new java.awt.Color(255, 255, 255));
        SubmitjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submitblackbutton.png"))); // NOI18N
        SubmitjButton.setBorder(null);
        SubmitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitjButtonActionPerformed(evt);
            }
        });
        add(SubmitjButton);
        SubmitjButton.setBounds(310, 390, 87, 41);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 380, 57, 57);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitjButtonActionPerformed

        
        TechnicalpersonworkRequest request = new TechnicalpersonworkRequest();
        request.setComponent(componentjTextField.getText());
        request.setIssue(issuejTextField.getText());
        request.setStatus("waiting");
        request.setSender(userAccount);
        request.setSubmitdate(new Date());
        request.setRequestDate(new Date());
        request.setResolution("waiting");
                
        
        
        Organization org = null;
        for(Network network : system.getNetworkList())
            for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList())
                    if(ent.getEnterpriseType().toString().equals("TechSupport"))
                        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
//                            if(organization == null){
//                                JOptionPane.showMessageDialog(this, "No organization. Please create an organization first","Error",JOptionPane.ERROR_MESSAGE);
//                            }
                                if(organization instanceof TechnicalPersonOrganization){
                                    org = organization;
                                    break;
                                }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        populatetable();
        
    }//GEN-LAST:event_SubmitjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_jButton1ActionPerformed

    public void populatetable(){
    
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);
            for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){    
            Object[] row = new Object[7];
            if(request instanceof TechnicalpersonworkRequest){
            row[0] = request.getRequestDate();
            row[1] = request.getReceiver();
            row[2] = request.getSender();
            row[3] = ((TechnicalpersonworkRequest) request).getIssue();
            row[4] = ((TechnicalpersonworkRequest) request).getComponent();
            row[5] = ((TechnicalpersonworkRequest) request).getResolution();
            row[6] = request.getStatus();
            
            
            model.addRow(row);
            }
        }
            
        jTable1.setSelectionBackground(Color.getHSBColor(0.2F, 0.1F, 0.2F));
        jTable1.setSelectionForeground(Color.white);
        }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitjButton;
    private javax.swing.JTextField componentjTextField;
    private javax.swing.JTextField issuejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
