/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CarOwner;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Interface.Login;
import java.util.HashMap;
import javax.swing.JPanel;
import org.javatuples.Pair;
import Maths.Calculations.Calculatedistance;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JComponent;

/**
 *
 * @author Vivek
 */
public class Estimatedprice extends javax.swing.JPanel {

    /**
     * Creates new form Estimatedprice
     */
    JPanel container;
    UserAccount useraccount;
    Organization organization;
    Object sourcename;
    Object destinationname;
    CarOwnerMenuPageJPanel lastpanel;
    Calculatedistance calc;
    double actualprice=1;
    Boolean flag=true;
    
    public Estimatedprice(JPanel container,UserAccount u,Organization o,Object o1,Object o2,CarOwnerMenuPageJPanel lastpanel) {
        initComponents();
        this.container = container;
        this.useraccount = u;
        this.organization = o;
        this.sourcename = o1;
        this.destinationname = o2;
        this.lastpanel = lastpanel;
        sourcelabel.setText(sourcename.toString());
        destinationelabel.setText(destinationname.toString());
        distanceestimate("M");
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sourcelabel = new javax.swing.JLabel();
        destinationelabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        distancetraveljLabel = new javax.swing.JLabel();
        estpricejLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        distancecombobox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Estimated price");
        add(jLabel1);
        jLabel1.setBounds(270, 40, 211, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Source");
        add(jLabel2);
        jLabel2.setBounds(220, 110, 63, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Destination");
        add(jLabel3);
        jLabel3.setBounds(220, 170, 104, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Distance traveling :");
        add(jLabel5);
        jLabel5.setBounds(220, 310, 176, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Estimated price quote :");
        add(jLabel6);
        jLabel6.setBounds(220, 360, 208, 22);

        sourcelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sourcelabel.setText("jLabel7");
        add(sourcelabel);
        sourcelabel.setBounds(430, 110, 210, 22);

        destinationelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        destinationelabel.setText("jLabel7");
        add(destinationelabel);
        destinationelabel.setBounds(430, 170, 180, 22);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(47, 401, 57, 57);

        distancetraveljLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        distancetraveljLabel.setText("jLabel7");
        add(distancetraveljLabel);
        distancetraveljLabel.setBounds(440, 310, 82, 25);

        estpricejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estpricejLabel.setText("$ ");
        add(estpricejLabel);
        estpricejLabel.setBounds(440, 360, 82, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Distance Unit:");
        add(jLabel7);
        jLabel7.setBounds(220, 230, 128, 22);

        distancecombobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        distancecombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Miles", "Kilometers" }));
        distancecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distancecomboboxActionPerformed(evt);
            }
        });
        add(distancecombobox);
        distancecombobox.setBounds(430, 230, 131, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        lastpanel.temp = actualprice;
        lastpanel.updatvalue();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void distancecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distancecomboboxActionPerformed
        Object miles = (Object) distancecombobox.getSelectedItem();

        distanceestimate(miles.toString());
    }//GEN-LAST:event_distancecomboboxActionPerformed

    
    public void distanceestimate(String metric){
    calc = new Calculatedistance();
    HashMap<String,Object> carsource = new HashMap<>();
    carsource = organization.getsourcedestinationBoston();
    
    Pair<Double,Double> sourcecordinate = (Pair) carsource.get(sourcename);
    Pair<Double,Double> destinationcordinate = (Pair) carsource.get(destinationname);
    char knots;
    if(metric.equals("Kilometers"))
            knots = 'K';
    else
            knots = 'M';
    
    Double priceest =  calc.distance(sourcecordinate.getValue0(),sourcecordinate.getValue1(),destinationcordinate.getValue0(),destinationcordinate.getValue1(),knots);
    
    String pattern = "#.###";
    DecimalFormat decimalformat = new DecimalFormat(pattern);
    String format = decimalformat.format(priceest);
    
    distancetraveljLabel.setText(format.toString());
    if(flag){
        final Double costpertravel = priceest;
        calculaterate(costpertravel);
        flag=false;
    }
    }
    
    public void calculaterate(double miles)
    {
    double price[] = {2,2.4,2.8,3.2,3.6,4.0,4.4,4.8,5.2,5.6,6.0};
    for(int x=0;x<10;x++)
    {
        if(price[x]<miles && price[x+1] > miles)
            actualprice = price[x];
    }
    estpricejLabel.setText(String.valueOf(actualprice));
    
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationelabel;
    private javax.swing.JComboBox distancecombobox;
    private javax.swing.JLabel distancetraveljLabel;
    private javax.swing.JLabel estpricejLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel sourcelabel;
    // End of variables declaration//GEN-END:variables
}
