/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CarOwner;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class Userprofile extends javax.swing.JPanel {

    /**
     * Creates new form Userprofile
     */
    JPanel container;
    UserAccount useraccount;
            
    public Userprofile(JPanel container,UserAccount useraccount) {
        initComponents();
        this.container = container;
        this.useraccount = useraccount;
        namejTextField.setText(useraccount.getPerson().getPersonName());
        genderjTextField.setText(useraccount.getPerson().getGender());
        phonejTextField.setText(String.valueOf(useraccount.getPerson().getPhonenumber()));
        addressjTextField.setText(useraccount.getPerson().getAddress());
        accountbalancejTextField.setText(String.valueOf(useraccount.getPayment()));
        namejTextField.setEnabled(false);
        genderjTextField.setEnabled(false);
        phonejTextField.setEnabled(false);
        addressjTextField.setEnabled(false);
        accountbalancejTextField.setEnabled(false);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        accountbalancejTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        genderjTextField = new javax.swing.JTextField();
        phonejTextField = new javax.swing.JTextField();
        addressjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("User Account");
        add(jLabel1);
        jLabel1.setBounds(320, 30, 170, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Address");
        add(jLabel2);
        jLabel2.setBounds(250, 280, 120, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        add(jLabel3);
        jLabel3.setBounds(250, 120, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gender");
        add(jLabel4);
        jLabel4.setBounds(250, 170, 100, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number");
        add(jLabel5);
        jLabel5.setBounds(250, 230, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Account Balance");
        add(jLabel6);
        jLabel6.setBounds(250, 340, 160, 40);

        accountbalancejTextField.setBackground(new java.awt.Color(204, 204, 204));
        add(accountbalancejTextField);
        accountbalancejTextField.setBounds(410, 340, 100, 30);

        namejTextField.setBackground(new java.awt.Color(204, 204, 204));
        add(namejTextField);
        namejTextField.setBounds(410, 130, 100, 30);

        genderjTextField.setBackground(new java.awt.Color(204, 204, 204));
        add(genderjTextField);
        genderjTextField.setBounds(410, 180, 100, 30);

        phonejTextField.setBackground(new java.awt.Color(204, 204, 204));
        phonejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonejTextFieldActionPerformed(evt);
            }
        });
        add(phonejTextField);
        phonejTextField.setBounds(410, 230, 100, 30);

        addressjTextField.setBackground(new java.awt.Color(204, 204, 204));
        addressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextFieldActionPerformed(evt);
            }
        });
        add(addressjTextField);
        addressjTextField.setBounds(410, 290, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editicon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8);
        jLabel8.setBounds(520, 290, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editicon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        add(jLabel9);
        jLabel9.setBounds(520, 230, 30, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(60, 410, 60, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(370, 410, 90, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void phonejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonejTextFieldActionPerformed

    private void addressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextFieldActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        phonejTextField.setEnabled(true);
        Color lightgrey = Color.white;
        phonejTextField.setBackground(lightgrey);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        addressjTextField.setEnabled(true);
        Color lightgrey = Color.white;
        addressjTextField.setBackground(lightgrey);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        useraccount.getPerson().setAddress(addressjTextField.getText());
        useraccount.getPerson().setPonenumber(Integer.parseInt(phonejTextField.getText()));
        JOptionPane.showMessageDialog(this, "User data saved");
        addressjTextField.setEnabled(false);
        phonejTextField.setEnabled(false);
        addressjTextField.setBackground(Color.LIGHT_GRAY);
        phonejTextField.setBackground(Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountbalancejTextField;
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JTextField genderjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField phonejTextField;
    // End of variables declaration//GEN-END:variables
}
