/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Caruser;

import Business.Enterprise.Enterprise;
import Business.Organization.CarownerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarOwnerWorkRequest;
import Business.WorkQueue.CarUserWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Maths.Calculations.Calculatedistance;
import java.awt.Color;
import java.text.DecimalFormat;
import org.javatuples.Pair;

/**
 *
 * @author Vivek
 */


public class schedulerideJPanel extends javax.swing.JPanel {

    /**
     * Creates new form schedulerideJPanel
     */
    JPanel container;
    UserAccount userAccount;
    Enterprise enterprise;
    Organization org;
    Calculatedistance calc;
    boolean flag=false;    
    boolean flag1=false;
    double actualprice=1;
    HashMap<String,Object> carsource = new HashMap<>();

    public schedulerideJPanel(JPanel container, UserAccount userAccount,Enterprise enterprise,Organization org) {
        initComponents();
        this.org = org;
        carsource = org.getsourcedestinationBoston();
        this.container = container;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        Date selectedDate = new Date();
        jXDatePicker1.getMonthView().setLowerBound(selectedDate);
        populatetable();
        populatesourcecombobox();
        populatedestinationcombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        commentjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        caruserjTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Sourcecombobox = new javax.swing.JComboBox();
        destinationjComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Schedule your ride");
        add(jLabel2);
        jLabel2.setBounds(200, 30, 240, 60);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Comments");
        add(jLabel3);
        jLabel3.setBounds(170, 400, 110, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Price");
        add(jLabel4);
        jLabel4.setBounds(170, 290, 50, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Source");
        add(jLabel5);
        jLabel5.setBounds(170, 190, 110, 30);
        add(commentjTextField);
        commentjTextField.setBounds(320, 400, 130, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submitblackbutton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(260, 461, 90, 40);

        caruserjTable.setBackground(new java.awt.Color(153, 204, 255));
        caruserjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Source", "Destination", "Requested Date", "Status", "Comment", "Ride amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(caruserjTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 630, 80);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(40, 440, 57, 50);

        Sourcecombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sourcecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcecomboboxActionPerformed(evt);
            }
        });
        add(Sourcecombobox);
        Sourcecombobox.setBounds(320, 200, 130, 22);

        destinationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        destinationjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationjComboBoxActionPerformed(evt);
            }
        });
        add(destinationjComboBox);
        destinationjComboBox.setBounds(320, 250, 130, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Destination");
        add(jLabel6);
        jLabel6.setBounds(170, 240, 120, 40);

        pricejLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(pricejLabel);
        pricejLabel.setBounds(360, 300, 40, 20);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("calculate Price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(460, 290, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date");
        add(jLabel7);
        jLabel7.setBounds(170, 350, 43, 22);
        add(jXDatePicker1);
        jXDatePicker1.setBounds(320, 350, 112, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("$");
        add(jLabel1);
        jLabel1.setBounds(350, 300, 10, 17);
    }// </editor-fold>//GEN-END:initComponents

    public void populatesourcecombobox(){
        Object destobj=null;
        if(flag1)
        destobj = (Object) destinationjComboBox.getSelectedItem();
        Object sourobj = (Object) Sourcecombobox.getSelectedItem();
        
        Sourcecombobox.removeAllItems();
        
        Set set = carsource.entrySet();
        Iterator iterator = set.iterator();
        while(iterator.hasNext()) {
        Map.Entry mentry = (Map.Entry)iterator.next();
            Sourcecombobox.addItem(mentry.getKey());  
        }
        if(flag1)
        Sourcecombobox.setSelectedItem(destobj);
        flag1=true;
    }
    
    public void populatedestinationcombobox(){
        Object destobj=null;
        if(flag)
        destobj = (Object) destinationjComboBox.getSelectedItem();
        Object sourobj = (Object) Sourcecombobox.getSelectedItem();
        destinationjComboBox.removeAllItems();
        
        Set set = carsource.entrySet();
        Iterator iterator = set.iterator();
        while(iterator.hasNext()) {
        Map.Entry mentry = (Map.Entry)iterator.next();
        Object strr = (Object) Sourcecombobox.getSelectedItem();
        if(!mentry.getKey().equals(strr.toString()))
            destinationjComboBox.addItem(mentry.getKey());  
        } 
        if(flag)
        destinationjComboBox.setSelectedItem(destobj);
        flag=true;
    }
    
    public void populatetable(){
    DefaultTableModel model = (DefaultTableModel) caruserjTable.getModel();
        
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[8];
            if(request instanceof CarOwnerWorkRequest)
            {
            row[0] = request.getSender();
            row[1] = request.getReceiver();
            row[2] = request.getSource();
            row[3] = request.getDestination();
            row[4] = request.getRequestDate();
            row[5] = request.getStatus();
            row[6] = request.getcomment();
            row[7] = ((CarOwnerWorkRequest) request).getRideamount();
            model.addRow(row);
            }
        }
        caruserjTable.setSelectionBackground(Color.getHSBColor(0.2F, 0.1F, 0.2F));
        caruserjTable.setSelectionForeground(Color.white);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Object source = (Object) Sourcecombobox.getSelectedItem();
        Object destination = (Object) destinationjComboBox.getSelectedItem();
        
        CarOwnerWorkRequest request = new CarOwnerWorkRequest();
        request.setSender(userAccount);
        request.setRequestDate(jXDatePicker1.getDate());
        request.setSource(source.toString());
        request.setDestination(destination.toString());
        request.setcomment(commentjTextField.getText());
        request.setStatus("Waiting");
        request.setRideamount(Double.parseDouble(pricejLabel.getText()));
        Random rand = new Random();
        int randomNum = rand.nextInt((10000 - 1000) + 1) + 1000;
        request.setWorkrequestId(randomNum);
       
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CarownerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        populatetable();
        clearfields();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void clearfields(){
        commentjTextField.setText("");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainCaruserpanel dwjp = (MainCaruserpanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SourcecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcecomboboxActionPerformed

    }//GEN-LAST:event_SourcecomboboxActionPerformed

    private void destinationjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationjComboBoxActionPerformed

        //populatedestinationcombobox();
        
        Object miles = (Object) destinationjComboBox.getSelectedItem();

        //distanceestimate("K");

        
        //       Object sourobj = (Object) Sourcecombobox.getSelectedItem();
        //
        //        Set set = carsource.entrySet();
        //        Iterator iterator = set.iterator();
        //        while(iterator.hasNext()) {
            //        Map.Entry mentry = (Map.Entry)iterator.next();
            //        if(!mentry.getKey().equals(sourobj.toString()))
            //             destinationjComboBox.addItem(mentry.getKey());
            //        }
    }//GEN-LAST:event_destinationjComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        distanceestimate();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void distanceestimate(){
    calc = new Calculatedistance();
    HashMap<String,Object> carsource = new HashMap<>();
    carsource = org.getsourcedestinationBoston();
    
    Object sourcename = (Object) Sourcecombobox.getSelectedItem();
    Object destinationname = (Object) destinationjComboBox.getSelectedItem();
    
    Pair<Double,Double> sourcecordinate = (Pair) carsource.get(sourcename);
    Pair<Double,Double> destinationcordinate = (Pair) carsource.get(destinationname);
    
    Double priceest =  calc.distance(sourcecordinate.getValue0(),sourcecordinate.getValue1(),destinationcordinate.getValue0(),destinationcordinate.getValue1(),'M');
    
    String pattern = "#.###";
    DecimalFormat decimalformat = new DecimalFormat(pattern);
    String format = decimalformat.format(priceest);
    
        final Double costpertravel = priceest;
        calculaterate(costpertravel);
    }

    public void calculaterate(double miles)
    {
    double price[] = {2,2.4,2.8,3.2,3.6,4.0,4.4,4.8,5.2,5.6,6.0,6.4,6.8,7.2,7.6,8.0};
    for(int x=0;x<15;x++)
    {
        if(price[x]<miles && price[x+1] > miles)
            actualprice = price[x];
    }
    pricejLabel.setText(String.valueOf(actualprice));
    
    }
       
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Sourcecombobox;
    private javax.swing.JTable caruserjTable;
    private javax.swing.JTextField commentjTextField;
    private javax.swing.JComboBox destinationjComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel pricejLabel;
    // End of variables declaration//GEN-END:variables
}
