/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expreiment;

import Business.Enterprise.Enterprise;
import Business.Organization.CarUserOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarUserWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXCollapsiblePane;
import java.awt.Dimension;


/**
 *
 * @author Vivek
 */
public class expreiment extends javax.swing.JPanel {

    /**
     * Creates new form expreiment
     */
        JPanel container;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    int seats;

    public expreiment(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        jXCollapsiblePane1.setLayout(new BorderLayout());
        jXCollapsiblePane1.add(jPanel2,BorderLayout.CENTER);
        requestjButton.addActionListener(jXCollapsiblePane1.getActionMap().get(JXCollapsiblePane.TOGGLE_ACTION));
        this.container = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        adminnamejLabel.setText(account.getPerson().getPersonName());
        
        populatecartypecombobox();
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jXCollapsiblePane1 = new org.jdesktop.swingx.JXCollapsiblePane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminnamejLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminrequestjTable = new javax.swing.JTable();
        cartypesjComboBox = new javax.swing.JComboBox();
        accomodatejLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sourcejTextField = new javax.swing.JTextField();
        destinationjTextField = new javax.swing.JTextField();
        commentjTextField = new javax.swing.JTextField();
        requestjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        approvejButton = new javax.swing.JButton();

        jPanel2.setLayout(null);

        jLabel3.setText("Approve requests");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 50, 90, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Confirm Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 160, 180, 50);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jXCollapsiblePane1.setCollapsed(true);
        add(jXCollapsiblePane1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logged in:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 40);

        adminnamejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminnamejLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminnamejLabel.setText("adminname");
        jPanel1.add(adminnamejLabel);
        adminnamejLabel.setBounds(130, 20, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Web Owner");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 0, 340, 50);

        adminrequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car", "Sender", "Receiver", "Source", "Destination", "Request Date", "Status", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adminrequestjTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 720, 110);

        cartypesjComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cartypesjComboBox.setForeground(new java.awt.Color(255, 255, 255));
        cartypesjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cartypesjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartypesjComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(cartypesjComboBox);
        cartypesjComboBox.setBounds(150, 270, 100, 20);

        accomodatejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accomodatejLabel.setForeground(new java.awt.Color(255, 255, 255));
        accomodatejLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        jPanel1.add(accomodatejLabel);
        accomodatejLabel.setBounds(150, 320, 40, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Source");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 260, 100, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Destination");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 290, 100, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Comments");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 330, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Car details");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 210, 140, 40);
        jPanel1.add(sourcejTextField);
        sourcejTextField.setBounds(490, 260, 120, 30);
        jPanel1.add(destinationjTextField);
        destinationjTextField.setBounds(490, 300, 120, 30);
        jPanel1.add(commentjTextField);
        commentjTextField.setBounds(490, 340, 200, 30);

        requestjButton.setBackground(new java.awt.Color(255, 255, 255));
        requestjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        requestjButton.setText("Request");
        requestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(requestjButton);
        requestjButton.setBounds(290, 410, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Car Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 250, 80, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Accomodate");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 310, 90, 50);

        approvejButton.setText("Approve Requests");
        jPanel1.add(approvejButton);
        approvejButton.setBounds(240, 490, 233, 50);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

     public void populatecartypecombobox()
    {
        HashMap<String,Integer> cartype = new HashMap<String,Integer>();
        cartype.put("Nisaan Rogue",6);
        cartype.put("Nisaan Chevrolet",4);
        cartype.put("Versa",2);
        cartype.put("Ford Fiesta",4);
        cartype.put("Toyota corolla",5);
        cartype.put("Honda Civic",3);
        cartype.put("GMC Canyon",2);
        cartype.put("Chevrolet silverado",4);

        cartypesjComboBox.removeAllItems();
        
        Set set = cartype.entrySet();
        Iterator iterator = set.iterator();
        while(iterator.hasNext()) {
        Map.Entry mentry = (Map.Entry)iterator.next();
        cartypesjComboBox.addItem(mentry.getKey());         
      }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) adminrequestjTable.getModel();
        
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[8];
            row[0] = request.getcar();
            row[1] = request.getSender();
            row[2] = request.getReceiver();
            row[3] = request.getSource();
            row[4] = request.getDestination();
            row[5] = request.getRequestDate();
            JOptionPane.showMessageDialog(this, request.getseats());
            //String result = ((CarUserWorkRequest) request).getTestResult();
            row[6] = request.getseats() == 0 ? "waiting" : "Completed";
            //row[6] = request.getStatus() == null ? "Waiting" : "Completed";
            row[7] = request.getcomment();
            model.addRow(row);
        }
        populateusersidetablle();
    }
     
    public void populateusersidetablle(){
    
     DefaultTableModel model = (DefaultTableModel) adminrequestjTable.getModel();
        
        
        //model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = request.getcar();
            row[1] = request.getSource();
            row[2] = request.getDestination();;
            model.addRow(row);
        }
    }
     
     
     
    private void cartypesjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartypesjComboBoxActionPerformed
        HashMap<String,Integer> cartype = new HashMap<String,Integer>();
        cartype.put("Nisaan Rogue",6);
        cartype.put("Nisaan Chevrolet",4);
        cartype.put("Versa",2);
        cartype.put("Ford Fiesta",4);
        cartype.put("Toyota corolla",5);
        cartype.put("Honda Civic",3);
        cartype.put("GMC Canyon",2);
        cartype.put("Chevrolet silverado",4);

        Object strr = (Object) cartypesjComboBox.getSelectedItem();
        if(strr == null)
        return;
        accomodatejLabel.setText(cartype.get(strr).toString());
        seats = (Integer) cartype.get(strr);
    }//GEN-LAST:event_cartypesjComboBoxActionPerformed

    private void requestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestjButtonActionPerformed

        Object strr = (Object) cartypesjComboBox.getSelectedItem();

        CarUserWorkRequest request = new CarUserWorkRequest();
        request.setSender(userAccount);
        request.setcar(strr.toString());
        request.setRequestDate(new Date());
        request.setSource(sourcejTextField.getText());
        request.setDestination(destinationjTextField.getText());
        request.setcomment(commentjTextField.getText());
        request.setseats(seats);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CarUserOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        populateRequestTable();
        clearfields();
    }//GEN-LAST:event_requestjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(this, "This is spartaaa");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(jXCollapsiblePane1.isCollapsed()){
            jPanel2.setPreferredSize(jPanel1.getSize());
        }
    }//GEN-LAST:event_formComponentResized

    public void clearfields()
    {
        sourcejTextField.setText("");
        destinationjTextField.setText("");
        commentjTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accomodatejLabel;
    private javax.swing.JLabel adminnamejLabel;
    private javax.swing.JTable adminrequestjTable;
    private javax.swing.JButton approvejButton;
    private javax.swing.JComboBox cartypesjComboBox;
    private javax.swing.JTextField commentjTextField;
    private javax.swing.JTextField destinationjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXCollapsiblePane jXCollapsiblePane1;
    private javax.swing.JButton requestjButton;
    private javax.swing.JTextField sourcejTextField;
    // End of variables declaration//GEN-END:variables
}
