/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.login;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.CarUserRole;
import Interface.Caruser.MainCaruserpanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Vivek
 */
public class Logincaruser extends javax.swing.JPanel {

    /**
     * Creates new form Logincaruser
     */
    Network system;
    Organization organization;
    JPanel container;
    DB4OUtil dB4OUtil;
    EcoSystem system1;
    public Logincaruser(JPanel userprocesscontainer, Network system,Organization organization,DB4OUtil dB4OUtil,EcoSystem system1) {
        initComponents();
        this.system = system;
        this.container = userprocesscontainer;
        this.organization = organization;
        this.dB4OUtil = dB4OUtil;
        this.system1 = system1;
        innerpanel.setVisible(false);
        submitjButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        phonejTextField = new javax.swing.JTextField();
        addressjTextField = new javax.swing.JTextField();
        submitjButton = new javax.swing.JButton();
        innerpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        checkusernamejButton = new javax.swing.JButton();
        passwordrjTextField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        malejRadioButton = new javax.swing.JRadioButton();
        femalejRadioButton = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Car User login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone number");

        namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextFieldActionPerformed(evt);
            }
        });
        namejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namejTextFieldKeyTyped(evt);
            }
        });

        phonejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonejTextFieldKeyTyped(evt);
            }
        });

        submitjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submitblackbutton.png"))); // NOI18N
        submitjButton.setBorder(null);
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        innerpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("UserName");

        usernamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamejTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        checkusernamejButton.setBackground(new java.awt.Color(0, 0, 0));
        checkusernamejButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkusernamejButton.setForeground(new java.awt.Color(255, 255, 255));
        checkusernamejButton.setText("Check username");
        checkusernamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkusernamejButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Confirm Password");

        javax.swing.GroupLayout innerpanelLayout = new javax.swing.GroupLayout(innerpanel);
        innerpanel.setLayout(innerpanelLayout);
        innerpanelLayout.setHorizontalGroup(
            innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(passwordrjTextField)
                    .addComponent(jPasswordField1))
                .addGap(53, 53, 53))
            .addGroup(innerpanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(checkusernamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innerpanelLayout.setVerticalGroup(
            innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordrjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(checkusernamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/confirmbtn.jpg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        malejRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(malejRadioButton);
        malejRadioButton.setSelected(true);
        malejRadioButton.setText("Male");

        femalejRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(femalejRadioButton);
        femalejRadioButton.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namejTextField)
                                    .addComponent(phonejTextField)
                                    .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(malejRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femalejRadioButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(innerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitjButton)
                        .addGap(269, 269, 269))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(malejRadioButton)
                            .addComponent(femalejRadioButton))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(innerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextFieldActionPerformed

     public void clearfields()
    {
    namejTextField.setEnabled(true);
    phonejTextField.setEnabled(true);
    addressjTextField.setEnabled(true);
    malejRadioButton.setEnabled(true);
    femalejRadioButton.setEnabled(true);
    namejTextField.setText("");
    passwordrjTextField.setText("");
    phonejTextField.setText("");
    addressjTextField.setText("");
    usernamejTextField.setText("");
    jPasswordField1.setText("");
    }
    
    
    private void usernamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamejTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Loginpage dwjp = (Loginpage) component;
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean flag=false;
        JTextField[] textFields = new JTextField[3];
        textFields[0] = namejTextField;
        textFields[1] = phonejTextField;
        textFields[2] = addressjTextField;
        
        for(int i=0;i<3;i++) {
            
            if (textFields[i].getText().equals("")) {
                flag=false;
                JOptionPane.showMessageDialog(this, "Fields cannot be blank.","Error",JOptionPane.ERROR_MESSAGE);
                break;
            } else if ((textFields[i].getText().equals("0"))) {
                flag=false;
                JOptionPane.showMessageDialog(this, "Values cannot be zero.Please re-enter the value","Error",JOptionPane.ERROR_MESSAGE);
                break;
            } else                 
                  flag=true;
            }

        if(phonejTextField.getText().length() != 10)
        {
            flag = false;
            JOptionPane.showMessageDialog(this, "Please insert 10 digit number","Phone number",JOptionPane.ERROR_MESSAGE);
        }

        if(flag){
            String regex = "^[[:A-Za-z:]]+( [[:A-Za-z:]]+)*$";
            boolean ok = Pattern.matches(regex, namejTextField.getText());
            if(!ok){
                flag = false;
                JOptionPane.showMessageDialog(this, "Input value is not correct");
            }
        }
        
        if(flag){
            innerpanel.setVisible(true);
            namejTextField.setEnabled(false);
            phonejTextField.setEnabled(false);
            addressjTextField.setEnabled(false);
            malejRadioButton.setEnabled(false);
            femalejRadioButton.setEnabled(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void checkusernamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkusernamejButtonActionPerformed
        

        char[] passwordCharArray = passwordrjTextField.getPassword();
        String passwordx = String.valueOf(passwordCharArray);
        char[] passwordCharArray1 = jPasswordField1.getPassword();
        String passwordx1 = String.valueOf(passwordCharArray1);        
        
         boolean statusx=true;
         for(Network network : system1.getNetworkList())
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
              for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                  statusx = org.getUserAccountDirectory().checkIfUsernameIsUnique(usernamejTextField.getText());
                     if(statusx){                        
                     }else{
                        statusx=false;
                        JOptionPane.showMessageDialog(this, "Username exists!! Please choose a different username","Error",JOptionPane.WARNING_MESSAGE);
                        return;
                     }
              }    
        
        for(Network network : system1.getNetworkList())
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                   statusx = enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(usernamejTextField.getText());
                 if(statusx){                        
                     }else{
                        statusx=false;
                        JOptionPane.showMessageDialog(this, "Username exists!! Please choose a different username","Error",JOptionPane.WARNING_MESSAGE);
                        return;
                     }
            }
        
        if(statusx){
            JOptionPane.showMessageDialog(null,"You can use this username");
            
            if(passwordx.equals(passwordx1))
            submitjButton.setEnabled(true);
        else
            JOptionPane.showMessageDialog(this, "Please provide the same password");
        }else{
            JOptionPane.showMessageDialog(null,"username exists !!! Please select a different username");
        }
        
    }//GEN-LAST:event_checkusernamejButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed

        String name = namejTextField.getText();
        String gender= null;
        if(malejRadioButton.isSelected())
            gender = "Male";
        if(femalejRadioButton.isSelected())
            gender = "Female";
        long phone = Long.parseLong(phonejTextField.getText());
        String address = addressjTextField.getText();
        String username = usernamejTextField.getText();
        //String password = passwordrjTextField.getText();
        char[] passwordCharArray = passwordrjTextField.getPassword();
        String passwordx = String.valueOf(passwordCharArray);



        Person per = organization.getPersonDirectory().createPerson(name, gender, phone, address, 500);
        organization.getUserAccountDirectory().createUserAccount(username, passwordx, null, per, new CarUserRole());
        dB4OUtil.storeSystem(system1);
        submitjButton.setEnabled(false);
        innerpanel.setVisible(false);
        clearfields();
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void namejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namejTextFieldKeyTyped
        char name = evt.getKeyChar();
        
        if (  !(Character.isAlphabetic(name)) && !(Character.isSpaceChar(name))  )
        evt.consume();
    }//GEN-LAST:event_namejTextFieldKeyTyped

    private void phonejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonejTextFieldKeyTyped
        char phone = evt.getKeyChar();
        if (!(Character.isDigit(phone)))
        evt.consume();
    }//GEN-LAST:event_phonejTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton checkusernamejButton;
    private javax.swing.JRadioButton femalejRadioButton;
    private javax.swing.JPanel innerpanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton malejRadioButton;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JPasswordField passwordrjTextField;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
