/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.login;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.CarOwnerRole;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Vivek
 */
public class Logincarowneruser extends javax.swing.JPanel {

    /**
     * Creates new form Loginuser
     */
    
    Network system;
    Organization organization;
    JPanel container;
    DB4OUtil dB4OUtil;
    EcoSystem system1;
    public Logincarowneruser(JPanel userprocesscontainer, Network system,Organization organization,DB4OUtil dB4OUtildB4OUtil,EcoSystem system1) {
        initComponents();
        this.system = system;
        this.container = userprocesscontainer;
        this.organization = organization;
        this.dB4OUtil = dB4OUtildB4OUtil;
        this.system1 = system1;
        innerpanel.setVisible(false);
        submitjButton.setEnabled(false);
        jButton1.setBackground(Color.yellow);
        namejTextField.setTransferHandler(null);
        phonejTextField.setTransferHandler(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        phonejTextField = new javax.swing.JTextField();
        addressjTextField = new javax.swing.JTextField();
        submitjButton = new javax.swing.JButton();
        innerpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        checkusernamejButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        passwordrjTextField = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        malejRadioButton = new javax.swing.JRadioButton();
        femalejRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Car Owner login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone number");

        namejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namejTextFieldFocusLost(evt);
            }
        });
        namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextFieldActionPerformed(evt);
            }
        });
        namejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namejTextFieldKeyTyped(evt);
            }
        });

        phonejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonejTextFieldKeyTyped(evt);
            }
        });

        submitjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submitblackbutton.png"))); // NOI18N
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        innerpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("UserName");

        usernamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamejTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        checkusernamejButton.setBackground(new java.awt.Color(0, 0, 0));
        checkusernamejButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkusernamejButton.setForeground(new java.awt.Color(255, 255, 255));
        checkusernamejButton.setText("Check username");
        checkusernamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkusernamejButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Confirm Password");

        javax.swing.GroupLayout innerpanelLayout = new javax.swing.GroupLayout(innerpanel);
        innerpanel.setLayout(innerpanelLayout);
        innerpanelLayout.setHorizontalGroup(
            innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerpanelLayout.createSequentialGroup()
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(innerpanelLayout.createSequentialGroup()
                        .addGap(96, 103, Short.MAX_VALUE)
                        .addComponent(checkusernamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(innerpanelLayout.createSequentialGroup()
                        .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(innerpanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerpanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField2)
                            .addComponent(usernamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(passwordrjTextField))))
                .addContainerGap())
        );
        innerpanelLayout.setVerticalGroup(
            innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passwordrjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(checkusernamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/confirmbtn.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        malejRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(malejRadioButton);
        malejRadioButton.setSelected(true);
        malejRadioButton.setText("Male");

        femalejRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(femalejRadioButton);
        femalejRadioButton.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(submitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namejTextField)
                                    .addComponent(phonejTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(malejRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(femalejRadioButton))
                                    .addComponent(addressjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(innerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(malejRadioButton)
                            .addComponent(femalejRadioButton))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(innerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextFieldActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed

        String name = namejTextField.getText();
        String gender= null;
        if(malejRadioButton.isSelected())
            gender = "Male";
        if(femalejRadioButton.isSelected())
            gender = "Female";
        long phone = Long.parseLong(phonejTextField.getText());
        String address = addressjTextField.getText();
        String username = usernamejTextField.getText();
        String password = passwordrjTextField.getText();
            
        Person per = organization.getPersonDirectory().createPerson(name, gender, phone, address, 200);
        organization.getUserAccountDirectory().createUserAccount(username, password, null, per, new CarOwnerRole());
        dB4OUtil.storeSystem(system1);
        submitjButton.setEnabled(false);
        innerpanel.setVisible(false);
        clearfields();
        
    }//GEN-LAST:event_submitjButtonActionPerformed

    public void clearfields()
    {
    namejTextField.setEnabled(true);
    phonejTextField.setEnabled(true);
    addressjTextField.setEnabled(true);
    malejRadioButton.setEnabled(true);
    femalejRadioButton.setEnabled(true);
    namejTextField.setText("");
    passwordrjTextField.setText("");
    phonejTextField.setText("");
    addressjTextField.setText("");
    usernamejTextField.setText("");
    jPasswordField2.setText("");
    }
    
    private void usernamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamejTextFieldActionPerformed

    private void checkusernamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkusernamejButtonActionPerformed

        char[] passwordCharArray = passwordrjTextField.getPassword();
        String passwordx = String.valueOf(passwordCharArray);
        char[] passwordCharArray1 = jPasswordField2.getPassword();
        String passwordx1 = String.valueOf(passwordCharArray1);        
        
         boolean statusx=true;
         for(Network network : system1.getNetworkList())
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
              for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                  statusx = org.getUserAccountDirectory().checkIfUsernameIsUnique(usernamejTextField.getText());
                     if(statusx){                        
                     }else{
                        statusx=false;
                        JOptionPane.showMessageDialog(this, "Username exists!! Please choose a different username","Error",JOptionPane.WARNING_MESSAGE);
                        return;
                     }
              }
         
        for(Network network : system1.getNetworkList())
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                   statusx = enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(usernamejTextField.getText());
                 if(statusx){                        
                     }else{
                        statusx=false;
                        JOptionPane.showMessageDialog(this, "Username exists!! Please choose a different username","Error",JOptionPane.WARNING_MESSAGE);
                        return;
                     }
            }
        
        if(statusx){
            JOptionPane.showMessageDialog(null,"You can use this username");
            
            if(passwordx.equals(passwordx1))
            submitjButton.setEnabled(true);
        else
            JOptionPane.showMessageDialog(this, "Please provide the same password");
        }else{
            JOptionPane.showMessageDialog(null,"username exists !!! Please select a different username");
        }
    }//GEN-LAST:event_checkusernamejButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        boolean flag=false;
        JTextField[] textFields = new JTextField[3];
        textFields[0] = namejTextField;
        textFields[1] = phonejTextField;
        textFields[2] = addressjTextField;
        
        for(int i=0;i<3;i++) {
            
            if (textFields[i].getText().equals("")) {
                flag=false;
                JOptionPane.showMessageDialog(this, "Fields cannot be blank.","Error",JOptionPane.ERROR_MESSAGE);
                break;
            } else if ((textFields[i].getText().equals("0"))) {
                flag=false;
                JOptionPane.showMessageDialog(this, "Values cannot be zero.Please re-enter the value","Error",JOptionPane.ERROR_MESSAGE);
                break;
            } else                 
                  flag=true;
            }

        if(phonejTextField.getText().length() != 10)
        {
            flag = false;
            JOptionPane.showMessageDialog(this, "Please insert 10 digit number","Phone number",JOptionPane.ERROR_MESSAGE);
                    
        }
        
        if(flag){
            String regex = "^[[:A-Za-z:]]+( [[:A-Za-z:]]+)*$";
            boolean ok = Pattern.matches(regex, namejTextField.getText());
            if(!ok){
                flag = false;
                JOptionPane.showMessageDialog(this, "Input value is not correct");
            }
        }
        
        if(flag){
            innerpanel.setVisible(true);
            namejTextField.setEnabled(false);
            phonejTextField.setEnabled(false);
            addressjTextField.setEnabled(false);
            malejRadioButton.setEnabled(false);
            femalejRadioButton.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namejTextFieldKeyTyped
        char name = evt.getKeyChar();
        if (  !(Character.isAlphabetic(name)) && !(Character.isSpaceChar(name))  )
        evt.consume();
        
    }//GEN-LAST:event_namejTextFieldKeyTyped

    private void phonejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonejTextFieldKeyTyped
        char phone = evt.getKeyChar();
        if (!(Character.isDigit(phone)))
        evt.consume();
        
    }//GEN-LAST:event_phonejTextFieldKeyTyped

    private void namejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namejTextFieldFocusLost
       
    }//GEN-LAST:event_namejTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton checkusernamejButton;
    private javax.swing.JRadioButton femalejRadioButton;
    private javax.swing.JPanel innerpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton malejRadioButton;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JPasswordField passwordrjTextField;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
